### ISSUE TITLE
Please add comments

### ISSUE THREAD

**Issue by Sriharivignesh** [cbuahin/PyQuadTree#1]
I like your implementation , but I am not able to understand how you have implemented the quad tree. Comments pertaining to that would be very helpful.

**Comment by cbuahin** [comment]
I have added some comments to explain the implementation. Let me know if you have any specific questions.

**Comment by Sriharivignesh** [comment]
Hey, thank you very much for taking your time and adding comments! Much appreciated! Will go through it this weekend...but based on a glance, everything looks very good!

**Comment by cbuahin** [comment]
Sounds good!
